AddonId: GogLibrary_Builtin
Packages:
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-24
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/GogLibrary_Builtin_2_2.pext
    Changelog:
      - Updated dependencies for Playnite 9
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-08
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/1.0/GogLibrary_Builtin_2_1.pext
    Changelog:
      - Authentication doesn't work properly
      - Updated to support Playnite 9 beta 2
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-03
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/1.0/GogLibrary_Builtin_2_0.pext
    Changelog:
      - Playnite 9 support
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-04
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/GogLibrary_Builtin_2_3.pext
    Changelog:
      - Fixed import of uninstalled games failing with strict privacy settings
  - Version: 2.4
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-22
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/GogLibrary_Builtin_2_4.pext
    Changelog:
      - Fixed some issues related to import of installed games
  - Version: 2.5
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-11-24
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/GogLibrary_Builtin_2_5.pext
    Changelog:
      - Fixed issue with some games (mainly those using DosBox) not starting properly
  - Version: 2.6
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-01-17
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/GogLibrary_Builtin_2_6.pext
    Changelog:
      - Fixed issue with metadata not downloading for some games