AddonId: HumbleLibrary_Builtin
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-03
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/1.0/HumbleLibrary_Builtin_2_0.pext
    Changelog:
      - Playnite 9 support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-08
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/1.0/HumbleLibrary_Builtin_2_1.pext
    Changelog:
      - Updated to support Playnite 9 beta 2
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-24
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/HumbleLibrary_Builtin_2_2.pext
    Changelog:
      - Updated dependencies for Playnite 9
  - Version: 3.0
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-01
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/HumbleLibrary_Builtin_3_0.pext
    Changelog:
      - Added support for new Humble App
      - Added support for new Humble Choice subscription
      - Improved general import speed
  - Version: 3.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-01
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/HumbleLibrary_Builtin_3_1.pext
    Changelog:
      - Fixed Humble library icon not showing up properly when set as missing game icon
  - Version: 3.2
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-02
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/HumbleLibrary_Builtin_3_2.pext
    Changelog:
      - Fixed Humble App being selectable install option for non-Humble games